### PR TITLE
Fixed Android app's theme not being applied, among other things

### LINKED ISSUE #13: Control color is not the default.
The control color on Android is coming up white for me and not the default color. I see means to change the BackgroundColor but not the color of the control itself.

### PR DESCRIPTION
**Pull request by MarcosCobena**
Hi!

I just wanted to give back because we've recently used this control and liked it.

This PR bundles:
- a reorganization of files, to avoid multiple if/endif in the same one, and simplify the process for future contributors, also helping those like me in macOS where VS for Mac doesn't support multi-targeting;
- fixed #13 and #11, although this last one would need more love because can't be modified from the final app;
- updated inner README to help others building under macOS; and
- updated NuGet version

I'm open for any comment you may see to improve.

And I hope you like it!

Thanks for your work,

—Marcos

### CODE REVIEW

**Comment by MarcosCobena** [comment]
After the thread at Twitter I've realized I didn't explain in depth what the PR actually implies:

My original concern was why the native control wasn't taking my app's theme as any other around. After digging with my mates @jacano and @sescalada, we noticed you were explicitly passing Android's Application.Context

https://github.com/dotMorten/XamarinFormsControls/blob/master/AutoSuggestBox/dotMorten.Xamarin.Forms.AutoSuggestBox/AutoSuggestBox.cs#L43

Simply changing such to your current Activity's fixes it.

So, I went on and tried to change the above. From Xamarin.Forms 2.5+ there's a recommendation of creating 1 single ctor. with receives a Context so X.F will automatically inject the correct one

https://docs.microsoft.com/es-es/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view#creating-the-custom-renderer-on-android

; however, you're actually instantiating the native control directly from the same upper-level AutoSuggestBox definition

https://github.com/dotMorten/XamarinFormsControls/blob/master/AutoSuggestBox/dotMorten.Xamarin.Forms.AutoSuggestBox/AutoSuggestBox.cs#L41

, instead of letting Custom Renderers do this job for you.

After trying stuff I ended up refactoring your code to follow Xamarin guidelines, and this' the main reason why I needed to split things up: there's no way to actually work with files filled of #if/#endif if multi-targeting's not supported from the IDE. Also, I had to copy every file from this project into ours, because it didn't work just referencing your project, as VS for Mac just builds the first target framework present in the array.

To help other future contributors comming by, I updated the inner README with how anyone could build the package under macOS, but I'm sure this won't eventually be needed as VS for Mac will get updated anytime soon.

After all this, I'd like to hear your opinion so we can decide which's the best path to follow. I'm sure anyone out there interested in the control and using it under Android will suffer the above mentioned bug, and this' my main priority currently, as I'd be happier referencing back a new package version pulled from NuGet.

Thanks for reading!

**Comment by MarcosCobena** [comment]
Hey @dotMorten just if you had some time to read the above. Thanks in advance :-)

**Comment by MarcosCobena** [comment]
Same as above, thanks again for your time

**Comment by concedev** [comment]
Hi, i need change color text on input but not working, i try your pull but crash app. any idea? 

Hola, yo necesito cambiar el color en el input pero no me funciona, probe el pull pero tampoco he logrado hacerlo funcionar alguna idea?

**Comment by MarcosCobena** [comment]
Hi @concedev,

Could you please share some code: the crash stack trace, errors output when building this PR and how you're trying to change the color? Also, could you please move this to a new bug?

Thanks!

**Comment by dotMorten** [comment]
Thank you for your contribution, but sorry but I'm going to have close this PR, as it seems to attempt multiple things, and also reorganizes the code. Please keep PRs to single issues and don't refactor everything without discussing in an issue first. I have to maintain the code long-term, so I prefer organizing code in ways that work for me.

I do appreciate the comments and suggestions you have, and will try and work through them bit-by-bit.

**Comment by dotMorten** [comment]
...Also sorry for the very slow response. Last year has been busy busy busy, but I'm trying to get back into bringing this control around to a proper v1.0

**Comment by dotMorten** [comment]
@MarcosCobena I believe all your suggestions has been incorporated at this point (just in a slightly different way). Thank you again! Let me know if anything else is missing.

**Pull request closed without merging**
